apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: events-web
 name: events-web-v2
spec:
 replicas: 1
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 25%
 selector:
   matchLabels:
     app: events-web
     ver: v2.0
 template:
   metadata:
     labels:
       app: events-web
       ver: v2.0
   spec:
     containers:
     - image: weidockerhub2026/events-website:v2.0
       name: events-web
       ports:
       - containerPort: 8080
       env:
         - name: SERVER
           value: "http://events-api-svc:8082"

